# This is a basic workflow to help you get started with Actions

name: update blog-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
    - name: update blog-ci
      run: |
        git config --global user.email "3437889+karuboniru@users.noreply.github.com"
        git config --global user.name "Commit bot"
        git clone --recurse-submodules https://${{ secrets.GH_TOKEN }}@github.com/karuboniru/blog_ci.git
        cd blog_ci/themes/fluid
        git pull https://github.com/karuboniru/hexo-theme-fluid.git master
        cd ../..
        git add .
        git commit -m "update submodule by $GITHUB_RUN_NUMBER at karuboniru/hexo-theme-fluid"
        git push
